name: Build LKM for KernelSU for Pong
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build-lkm:
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: android12-5.10
      ddk_release: '20260313'

  build-ksuinit:
    uses: ./.github/workflows/ksuinit.yml

  root-img:
    runs-on: ubuntu-latest
    needs:
      - build-lkm
      - build-ksuinit
    steps:
      - name: Checkout
        uses: actions/checkout@v6
  
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8

      - name: Patch in module
        run: |
          ls -lh

          mv -f ./ksuinit/**/release/ksuinit ksuinit
          mv -f ./**/*_kernelsu.ko ksun.ko

          chmod -R 755 AIK
          cd AIK
          ./unpackimg.sh ../pong.img
          mv -f ./ramdisk/init ./ramdisk/init.real
          cp -f ../ksuinit ./ramdisk/init || exit 1
          cp -f ../ksun.ko ./ramdisk/kernelsu.ko || exit 1
          chmod 755 ./ramdisk/init ./ramdisk/kernelsu.ko || exit 1
          ./repackimg.sh

          cp -f image-new.img ../ksun-pong.img || exit 1

      - name: Upload rooted img
        uses: actions/upload-artifact@v5
        with:
          name: ksun-pong_${{ github.run_number }}
          path: ksun-pong.img
